uploading lasagna masters exercises solution
JuanVimon3/exercism-javascript pull request #5
Opened 2023-02-27 16:12 UTC by JuanVimon3

2023-03-10 16:36 UTC, gualopezb requested changes

2023-03-10 16:36 UTC, gualopezb commented on lasagna-master/lasagna-master.js
> +import { createUnzip } from "zlib"
This function doesn't seem to be used anywhere.

2023-03-10 16:36 UTC, gualopezb commented on lasagna-master/lasagna-master.js
> +  }else{
This `else` branch is not necessary. I think the linter should probably catch that error up.

2023-03-10 16:36 UTC, gualopezb commented on lasagna-master/lasagna-master.js
> +for(let i = 0; i < layers.length; i++) {
Let's refactor this using the array's filter method.
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/filter

2023-03-10 16:36 UTC, gualopezb commented on lasagna-master/lasagna-master.js
> +}
Please add an empty line at the bottom of the file.

2023-03-10 16:36 UTC, gualopezb commented on lasagna-master/.eslintrc
> +  "extends": "@exercism/eslint-config-javascript",
@JuanVimon3 this should be "airbnb" in order to use their styling conventions for eslint.

2023-03-10 16:36 UTC, gualopezb commented on lasagna-master/lasagna-master.js
> +export function cookingStatus(time) {
Once you add the airbnb config properly to the .eslintrc file, you should update this function accordingly.

2023-03-11 15:32 UTC, gualopezb commented on lasagna-master/lasagna-master.js
> +// eslint-disable-next-line no-unused-vars
In this case, I think we should just delete line 4 instead of turning off the linter rule.

2023-04-01 20:10 UTC, gualopezb requested changes

2023-04-01 20:10 UTC, gualopezb commented on lasagna-master/lasagna-master.js
> +  } return { sauce, noodles };
Please put this return in its own line.

2023-04-01 20:12 UTC, gualopezb commented on lasagna-master/lasagna-master.js
> +for(let i = 0; i < layers.length; i++) {
@JuanVimon3 please address this suggestion also when you get a chance.

2023-04-04 15:31 UTC, JuanVimon3 commented on lasagna-master/lasagna-master.js
> +  }else{
![image](https://user-images.githubusercontent.com/111032081/229842766-221c89df-a1e0-472d-bfdd-8c78707970f0.png)

2023-04-17 23:04 UTC, gualopezb approved these changes

2023-04-17 23:07 UTC, merged